### ISSUE TITLE
Load routes from YAML on startup

### ISSUE THREAD

**Issue by maxsumrall** [verygoodsecurity/vgs-satellite#120]
## Problem statement

To have a local test environment in CI, I'd like to be able to load a configuration YAML rather than rely on setting up the routes each time in the UI. If I can do this, then I can include this in my project and source it in the docker container, s.t. when the satellite container starts, it loads routes defined in the supplied YAML. 

Maybe this is already supported, but then it's not documented. 

## Advised solution

Support (or document if supported) a way to load routes from a supplied YAML file. 

## Testing scenarios
Given a YAML file with routes (which was generated by exporting from VGS), when starting a fresh docker container running satellite, have the routes already loaded from this file.

**Comment by aslepakurov** [comment]
Hey, @maxsumrall, thanks for request.
We added YAML load in our backlog.
At the moment you can use our route CRUD, that manages configurations using JSON

```
curl 'http://localhost:8089/route' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-binary '{"data":{"attributes":{"destination_override_endpoint":"*","host_endpoint":"echo\\.apps\\.verygood\\.systems","port":80,"protocol":"http","source_endpoint":"*","transport":"HTTP","entries":[{"operation":"REDACT","phase":"REQUEST","public_token_generator":"UUID","targets":["body"],"token_manager":"PERSISTENT","transformer":"JSON_PATH","transformer_config":["$.foo"],"filter_id":"127","config":{"rules":[{"expression":{"field":"PathInfo","type":"string","operator":"matches","values":["/post"]}},{"expression":{"field":"ContentType","type":"string","operator":"equals","values":["application/json"]}}],"condition":"AND"},"classifiers":{},"transformer_config_map":null}],"tags":{"name":"test-route","source":"vgs-satellite"}},"type":"rule-chains"}}'
```

**Comment by aslepakurov** [comment]
Hey @maxsumrall, Happy New Year and a quick update!
We took this task into current iteration cycle, so we might have this in Satellite by the end of this week, start of the next.

**Comment by chris-dekker** [comment]
Thanks for the quick update, @aslepakurov ! I see it's been merged and released already. Any idea when we can expect the new release on Docker Hub? Looking forward to integrating it in our CI pipeline!

**Comment by aslepakurov** [comment]
Hey, @chris-dekker. Docker release would be ready today. I will share link here as soon as we would have it on Docker hub.

**Comment by aslepakurov** [comment]
Feature is now on [Dockerhub](https://hub.docker.com/repository/docker/verygood/satellite/tags?page=1&ordering=last_updated&name=1.3.0) and [Releases](https://github.com/verygoodsecurity/vgs-satellite/releases/tag/1.3.0) in scope of https://github.com/verygoodsecurity/vgs-satellite/pull/131
