### ISSUE TITLE
Regarding regexp match for upstream localhost url in forward proxy

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#156]
## Problem statement
Its a question really, not any issue. What is the upstream host regexp for a request to localhost url?
![Screenshot 2021-02-06 at 10 51 59](https://user-images.githubusercontent.com/69784585/107109828-5c0ad280-6869-11eb-863a-5faa8f8ef232.png)

I want a route to work for a localhost url, like `http://127.0.0.1:9006`. This is for local testing only with the VGS satellite.

**Comment by devansh-dalal** [comment]
Small experiment, I did, when I do 
`curl 'http://127.0.0.1:9006/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"number": "9914216697093874242"}'` with upstream host=`127.0.0.1` in route config yaml, it does not work as expected

vs

`curl 'http://localhost:9006/post?a=b' -k -x localhost:9099 -H "Content-type: application/json" -d '{"number": "9914216697093874242"}'` with upstream host=`localhost`, it does apply the filter as expected.

**Comment by rozenbom** [comment]
Hi @devansh-dalal, there are 2 parts here. The first one is the same as in https://github.com/verygoodsecurity/vgs-satellite/issues/150: "localhost"/127.0.0.1 will not work. The second part - it is not possible to configure a port for the upstream for now. It's a known issue we will fix it soon.

**Comment by devansh-dalal** [comment]
The major use case of VGS satellite is that we have local testing and development going on and hence have local source and destination servers running and VGS satellite has to route local REST calls properly for it to be successful. cc @rozenbom

**Comment by rozenbom** [comment]
Same as in #150 you can use the host name/ip address of the host machine (docker.for.mac.localhost if you on mac) or just refer docker-compose services (https://docs.docker.com/compose/networking/).
