### ISSUE TITLE
Regarding viewing/recording logs for satellite docker

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#159]
## Problem statement
Is there a way to view the logs as in electron app for satellite docker? The reason is, we do our development with container and want to have some UI like as shown in VGS dashboard.

**Comment by rozenbom** [comment]
Hi @devansh-dalal, the Docker image does not have any UI. You can use VGS Satellite management API to get access to all the logs/events if you like. By default, the management API is accessible on 8089-port. You can visit `http://localhost:8089/apidocs` to get the API docs. If you need the UI you can use the Electron app.

**Comment by devansh-dalal** [comment]
`404: Not Found` when I visit `http://localhost:8089/apidocs` in browser. VGS satellite is running in docker.

**Comment by rozenbom** [comment]
> `404: Not Found` when I visit `http://localhost:8089/apidocs` in browser. VGS satellite is running in docker.

Please make sure you've pulled the latest version of the image - we released the docs recently.
