### ISSUE TITLE
Regarding how to apply a filter on generic url

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#163]
## Problem statement
What is the problem in enabling `.*` and apply a bunch of filters on every request. I know its not possible to do do that in dashboard. But this can be very helpful in satellite and local debugging?

**Comment by rozenbom** [comment]
Hi @devansh-dalal, do you mean upsteam host for outbound routes?

**Comment by devansh-dalal** [comment]
yes

**Comment by devansh-dalal** [comment]
where are docs for the regexp matching of VGS satellite? I am having issues using simple use cases which works in VGS dashboard.
