### ISSUE TITLE
Management API not accessible inside docker-compose

### ISSUE THREAD

**Issue by chris-dekker** [verygoodsecurity/vgs-satellite#172]
## Problem statement
It looks like the management API (default: 8089) is only accessible from `localhost` and any ip address (see: https://github.com/verygoodsecurity/vgs-satellite/blob/master/satellite/web_application.py#L78).

Inside docker-compose each service has its own DNS hostname. In our case we need to call VGS's management API from a different container by its hostname, which leads to a 404.

## Advised solution
Please remove this localhost check or make it optional via a startup- or environment parameter.

**Comment by UlyanaFalach** [comment]
Hi @chris-dekker, we'll remove this check next week. Thanks for pointing our attention to this.

**Comment by chris-dekker** [comment]
Awesome! Thanks. Looking forward to the next Docker Hub release :)

**Comment by chris-dekker** [comment]
Thanks for the quick fix @rozenbom ! Any hint on when the next release will be up on Docker Hub?

**Comment by rozenbom** [comment]
Hi @chris-dekker, it's released.
