### ISSUE TITLE
DSL support for configuring routes

### ISSUE THREAD

**Issue by ilovetea** [verygoodsecurity/vgs-satellite#95]
## Problem statement
I'd like to configure routes programatically via DSL support rather than using UI 
## Advised solution
(insert text here)
## Testing scenarios
(insert text here)

## Tips (see below)
<details>
  <summary>Click to expand</summary>

  A proper GH issue contains the following:
  - Clear problem statement. No vague descriptions. Explains why the change is needed
  - Advised solution. Make sure give detailed explanation
  - Links to other engineering artifacts
   - Previous issues
   - Other pull requests
   - Rollbar tickets
   - Discussions in Slack
   - Spec documents
  - Labels that mark the following
   - Type (bug, enhancement)
   - Project scope (#ui, #proxy, #api, #tests...)
   - Process related activities (needs review, don’t merge)
   - Important stuff (breaking change, urgent)
</details>

**Comment by rozenbom** [comment]
Same as on the dashboard you can configure routes via YAML config.
